# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='base58',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
