# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 11:15
from __future__ import unicode_literals

import codebin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebin', '0002_snippet_base58'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='save_name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='base58',
            field=models.CharField(default=codebin.models.make_base58, editable=False, max_length=64),
        ),
    ]
