# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebin', '0005_snippet_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='last_edited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
