# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:44
from __future__ import unicode_literals

import codebin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebin', '0006_snippet_last_edited_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='id',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='base58',
            field=models.CharField(default=codebin.models.make_base58, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
